default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DB_DEV_NAME']%>

test:
  <<: *default
  database: <%= ENV['DB_TEST_NAME']%>

production:
  <<: *default
  database: <%= ENV['DB_PRO_NAME']%>
  